"""
Sync the PM-managed Google Sheet of KB entries into general_kb.yaml.

PM workflow (see KB_PM_GUIDE.md):
  1. PM adds rows to the shared sheet with status="draft"
  2. PM sets status="ready" when an entry is finished and reviewed
  3. This script reads all status="ready" rows, validates them, writes the
     entries into src/llm/prompts/general_kb.yaml, and writes validation
     errors back to the sheet's `notes` column so the PM sees them.

After the yaml is updated, run scripts/kb_ingest.py to re-embed and
upsert into the database.

Usage:
  python scripts/sheet_to_yaml.py
  python scripts/sheet_to_yaml.py --dry-run       # validate only, no yaml write
  python scripts/sheet_to_yaml.py --promote       # also flip status: ready -> live

Required env:
  KB_SHEET_ID            spreadsheet id from the sheet URL
  KB_SHEET_WORKSHEET     worksheet (tab) name; defaults to "entries"
  GOOGLE_APPLICATION_CREDENTIALS path to service-account JSON

Expected sheet columns (case-insensitive header in row 1, in any order):
  id, domain, content, keywords_en, keywords_cn, citations, status, notes

Multi-value columns (keywords_en, keywords_cn, citations) accept either
a comma-separated string or a Sheets-multiline cell.

The script is conservative: errors are reported per-row to the `notes`
column. The yaml is only written if every status="ready" row passes
validation — partial writes are rejected to keep the yaml consistent.
"""

import argparse
import os
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

YAML_PATH = ROOT / "src" / "llm" / "prompts" / "general_kb.yaml"

VALID_DOMAINS = ("care", "behavior", "stage", "region", "nutrition", "breed_care")
REQUIRED_COLS = ("id", "domain", "content")
MULTI_VALUE_COLS = ("keywords_en", "keywords_cn", "citations")
OPTIONAL_COLS = ("keywords_en", "keywords_cn", "citations", "status", "notes")


def _split_multi(cell: str) -> list[str]:
    """Accept either comma- or newline-separated values in a sheet cell."""
    if not cell:
        return []
    raw = cell.replace("\r\n", "\n").replace("\n", ",")
    return [piece.strip() for piece in raw.split(",") if piece.strip()]


def _validate(row: dict, all_ids: set[str], lineno: int) -> list[str]:
    """Return list of human-readable error strings, empty if row is valid."""
    errors: list[str] = []

    for col in REQUIRED_COLS:
        v = row.get(col, "")
        if not v or not str(v).strip():
            errors.append(f"required column '{col}' is empty")

    if errors:
        return errors

    if row["domain"] not in VALID_DOMAINS:
        errors.append(
            f"domain={row['domain']!r} is not one of {VALID_DOMAINS}"
        )

    content = str(row["content"]).strip()
    if len(content.split()) < 30:
        errors.append(
            f"content is too short ({len(content.split())} words; need >= 30)"
        )
    if len(content.split()) > 250:
        errors.append(
            f"content is too long ({len(content.split())} words; keep <= 250)"
        )

    id_ = str(row["id"]).strip()
    if not id_.replace("_", "").isalnum() or not id_.islower():
        errors.append(
            f"id={id_!r} must be lowercase snake_case (a-z, 0-9, underscore)"
        )
    if id_ in all_ids:
        errors.append(f"id={id_!r} is a duplicate of an earlier row")

    return errors


def _build_yaml_entry(row: dict) -> dict:
    """Convert a validated sheet row into the yaml entry shape."""
    return {
        "id": str(row["id"]).strip(),
        "domain": str(row["domain"]).strip(),
        "keywords_en": _split_multi(str(row.get("keywords_en", ""))),
        "keywords_cn": _split_multi(str(row.get("keywords_cn", ""))),
        "content": str(row["content"]).strip(),
        "citations": _split_multi(str(row.get("citations", ""))),
    }


def _write_yaml(entries: list[dict]) -> None:
    """Write yaml in a stable order — first by domain, then by id within domain."""
    sorted_entries = sorted(entries, key=lambda e: (e["domain"], e["id"]))

    # Reproduce the file's existing header verbatim so we don't drop the
    # operator-facing documentation.
    header = """\
# General pet-care knowledge base.
#
# Populated by `python scripts/kb_ingest.py` which:
#   1. Reads this file
#   2. Calls gemini text-embedding-004 on the `content` field
#   3. Upserts each entry into the general_kb_entry table
#
# At retrieval time (src/memory/kb_retrieval.py) we do a 3-branch hybrid:
#   - vector cosine top-k over `content` embedding
#   - postgres FTS top-k over `content`
#   - exact array match over keywords_en / keywords_cn
# Results are fused via RRF and injected into <retrieved_general_knowledge>.
#
# This file is regenerated by scripts/sheet_to_yaml.py from the
# PM-managed Google Sheet. Hand-edits will be overwritten on next sync.
# To add content, see KB_PM_GUIDE.md.

entries:
"""
    body = yaml.safe_dump(
        sorted_entries,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
        width=88,
    )
    # safe_dump emits at column 0; the existing file has 2-space indent on
    # entry list items. Normalise by re-emitting under the entries: key.
    out = header + "\n".join("  " + line if line.strip() else "" for line in body.splitlines()) + "\n"
    YAML_PATH.write_text(out, encoding="utf-8")


def _connect_sheet():
    """Lazy import gspread so the script gives a clear error message if the
    optional dependency isn't installed."""
    try:
        import gspread  # type: ignore[import-not-found]
        from google.oauth2.service_account import Credentials  # type: ignore[import-not-found]
    except ImportError as exc:
        raise RuntimeError(
            "scripts/sheet_to_yaml.py requires the kb_sync optional deps. "
            "Install with: pip install '.[kb_sync]'"
        ) from exc

    sheet_id = os.environ.get("KB_SHEET_ID", "").strip()
    if not sheet_id:
        raise RuntimeError("KB_SHEET_ID env var is required")

    creds_path = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS", "").strip()
    if not creds_path or not Path(creds_path).is_file():
        raise RuntimeError(
            "GOOGLE_APPLICATION_CREDENTIALS must point to a service-account JSON "
            "with read+write access to the sheet."
        )

    scopes = [
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/drive.readonly",
    ]
    creds = Credentials.from_service_account_file(creds_path, scopes=scopes)
    client = gspread.authorize(creds)
    worksheet_name = os.environ.get("KB_SHEET_WORKSHEET", "entries").strip() or "entries"
    return client.open_by_key(sheet_id).worksheet(worksheet_name)


def _read_rows(worksheet) -> tuple[list[dict], list[str]]:
    """Return (rows, header_cols). Rows are dicts keyed by lowercase header."""
    raw = worksheet.get_all_values()
    if not raw:
        return [], []
    header_cols = [c.strip().lower() for c in raw[0]]
    rows: list[dict] = []
    for r in raw[1:]:
        # Pad short rows so missing-tail columns are empty strings, not KeyErrors.
        padded = r + [""] * (len(header_cols) - len(r))
        rows.append(dict(zip(header_cols, padded)))
    return rows, header_cols


def _write_notes_back(worksheet, header_cols: list[str], errors_by_row: dict[int, str]) -> None:
    """Write per-row validation messages back into the sheet's `notes` column.
    Row numbers are 1-indexed and account for the header at row 1."""
    if "notes" not in header_cols:
        print("[sheet_to_yaml] sheet has no `notes` column — skipping error feedback")
        return
    col_idx = header_cols.index("notes") + 1
    for row_num, msg in errors_by_row.items():
        worksheet.update_cell(row_num, col_idx, msg)


def _maybe_promote(worksheet, header_cols: list[str], promoted_rows: list[int]) -> None:
    """Optional: flip status ready -> live for rows that made it into the yaml."""
    if "status" not in header_cols:
        return
    col_idx = header_cols.index("status") + 1
    for row_num in promoted_rows:
        worksheet.update_cell(row_num, col_idx, "live")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="validate only, no yaml write")
    parser.add_argument(
        "--promote",
        action="store_true",
        help="after successful yaml write, flip sheet status ready -> live",
    )
    args = parser.parse_args()

    worksheet = _connect_sheet()
    rows, header_cols = _read_rows(worksheet)
    if not rows:
        print("[sheet_to_yaml] sheet is empty.")
        return 0

    # Only sync status=ready rows.
    ready_rows: list[tuple[int, dict]] = []
    for i, row in enumerate(rows, start=2):  # +2 because header is row 1
        status = (row.get("status", "") or "").strip().lower()
        if status == "ready":
            ready_rows.append((i, row))

    if not ready_rows:
        print("[sheet_to_yaml] no rows with status=ready. Exiting.")
        return 0

    all_ids: set[str] = set()
    errors_by_row: dict[int, str] = {}
    valid_entries: list[dict] = []
    promoted_rows: list[int] = []

    for lineno, row in ready_rows:
        errs = _validate(row, all_ids, lineno)
        if errs:
            errors_by_row[lineno] = " | ".join(errs)
            continue
        all_ids.add(str(row["id"]).strip())
        valid_entries.append(_build_yaml_entry(row))
        promoted_rows.append(lineno)

    # Surface errors to the sheet so PM sees them immediately.
    _write_notes_back(worksheet, header_cols, errors_by_row)

    # Also clear notes on rows that passed (avoid stale error messages).
    if "notes" in header_cols:
        col_idx = header_cols.index("notes") + 1
        for row_num in promoted_rows:
            worksheet.update_cell(row_num, col_idx, "")

    if errors_by_row:
        print(
            f"[sheet_to_yaml] {len(errors_by_row)} row(s) failed validation; "
            f"see the sheet's `notes` column. Yaml NOT written.",
            file=sys.stderr,
        )
        return 1

    print(f"[sheet_to_yaml] {len(valid_entries)} row(s) ready to sync.")

    # We also keep any existing yaml entries that are NOT in the sheet
    # (manually-curated entries from the seed commit). Sheet wins on conflict.
    existing = _load_existing_entries()
    sheet_ids = {e["id"] for e in valid_entries}
    merged = [e for e in existing if e["id"] not in sheet_ids] + valid_entries
    print(
        f"[sheet_to_yaml] merging: {len(existing)} existing yaml entries + "
        f"{len(valid_entries)} from sheet = {len(merged)} total "
        f"({len(existing) - (len(merged) - len(valid_entries))} overwritten by sheet)"
    )

    if args.dry_run:
        print("[sheet_to_yaml] --dry-run: skipping yaml write.")
        return 0

    _write_yaml(merged)
    print(f"[sheet_to_yaml] wrote {YAML_PATH.relative_to(ROOT)}")

    if args.promote:
        _maybe_promote(worksheet, header_cols, promoted_rows)
        print(f"[sheet_to_yaml] promoted {len(promoted_rows)} sheet rows: ready -> live")

    return 0


def _load_existing_entries() -> list[dict]:
    if not YAML_PATH.exists():
        return []
    with YAML_PATH.open("r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    return list(data.get("entries") or [])


if __name__ == "__main__":
    sys.exit(main())
